diccionariosProyectos/base_siteV2/siteV2/alcool/urls.py
from django.urls import path
from . import views
app_name = 'alcool'
urlpatterns = [
    path('', views.alcool, name="index"),

        ]

diccionariosProyectos/base_siteV2/siteV2/main/urls.py
from django.urls import path
from . import views
app_name = 'main'
urlpatterns = [
    path('', views.index,name="index"),
]

diccionariosProyectos/base_siteV2/siteV2/menu/urls.py
from django.urls import path
from . import views
app_name = 'menu'
urlpatterns = [
    path('', views.menu, name="index"),

        ]

diccionariosProyectos/base_siteV2/siteV2/siteV2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include("menu.urls")),
    path('alcool/', include("alcool.urls")),
    path('', include('main.urls')),


]

diccionariosProyectos/base_siteV2/siteV2/alcool/models.py
from django.db import models

class Nouvelle_objet_alcool(models.Model):
        nom_objet = models.CharField(max_length=200)
        prix = models.FloatField(default=0)
        ingredient = models.CharField(max_length=200, blank=True)
        origine = models.CharField(max_length=200, blank=True)
        commentaire = models.CharField(max_length=200, blank=True)
        categorie = models.ManyToManyField("Categorie",related_name="Objet")
        def __str__(self):
                return self.nom_objet
class Categorie(models.Model):
        nom = models.CharField(max_length=100)
        def __str__(self):
                return self.nom

diccionariosProyectos/base_siteV2/siteV2/main/models.py
from django.db import models

# Create your models here.

diccionariosProyectos/base_siteV2/siteV2/menu/models.py
from django.db import models


class Nouvelle_objet(models.Model):
        nom_objet = models.CharField(max_length=200)
        prix = models.FloatField(default=0)
        ingredient = models.CharField(max_length=200, blank=True)
        origine = models.CharField(max_length=200, blank=True)
        commentaire = models.CharField(max_length=200, blank=True)
        categorie = models.ManyToManyField("Categorie",related_name="Objet")
        def __str__(self):
                return self.nom_objet
class Categorie(models.Model):
        nom = models.CharField(max_length=100)
        def __str__(self):
                return self.nom

diccionariosProyectos/base_siteV2/siteV2/alcool/views.py
from django.shortcuts import render

from .models import Nouvelle_objet_alcool

def alcool(request):
    coktails = Nouvelle_objet_alcool.objects.filter(categorie__id__contains=4)
    spiritueux = Nouvelle_objet_alcool.objects.filter(categorie__id__contains=1)
    coktails_sans_alcools = Nouvelle_objet_alcool.objects.filter(categorie__id__contains=5)
    vins_rouges = Nouvelle_objet_alcool.objects.filter(categorie__id__contains=2)
    vins_blancs = Nouvelle_objet_alcool.objects.filter(categorie__id__contains=3)
    section = {"coktails":coktails,
               "spiritueux":spiritueux,
               "coktails_sans_alcools": coktails_sans_alcools,
               "vins_rouges": vins_rouges,
               "vins_blancs": vins_blancs,
               }

    return render(request, "alcool/index.html", section)

diccionariosProyectos/base_siteV2/siteV2/main/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'main/index.html')

diccionariosProyectos/base_siteV2/siteV2/menu/views.py
from django.shortcuts import render
from .models import Nouvelle_objet

def menu(request):
        entrees = Nouvelle_objet.objects.filter(categorie__id__contains=1)
        plats = Nouvelle_objet.objects.filter(categorie__id__contains=2)
        suggestion_plats = Nouvelle_objet.objects.filter(categorie__id__contains=6)
        desserts = Nouvelle_objet.objects.filter(categorie__id__contains=7)
        plat_enfants = Nouvelle_objet.objects.filter(categorie__id__contains=9)
        section = {
            "entrees": entrees,
            "plats": plats,
            "suggestion_plats": suggestion_plats,
            "desserts": desserts,
            "plat_enfants": plat_enfants,

            }
        return render(request,"menu/index.html",section)

diccionariosProyectos/base_siteV2/siteV2/alcool/templates/alcool/base.html
{% load static %}
<html lang="fr">

<head>

    <meta charset="UTF-8">
    <title>Menu Restaurant</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'alcool/style.css'%}">
</head>
<body>
    <h1>Le  Restaurant</h1>
    <div>
        <img class="logo" src=" {% static 'alcool/images/restaurant_orange.png' %}">
    </div>

        <div class="separateur"></div>
{%block content %} {% endblock content %}
        <div class="frame_position">
            <a href="{% url 'main:index' %}"> Info</a>
            <a href="{% url 'menu:index' %}"> Menu</a>
            <a href="{% url 'alcool:index' %}"> Apéritif et Vins</a>
        </div>


</body>
</html>

diccionariosProyectos/base_siteV2/siteV2/alcool/templates/alcool/index.html
{%extends "alcool/base.html"%}



{%block content %}
<div class="ensemble">
    <h2>Coktail</h2>
    <div class="section">
        {% for coktail  in coktails %}
        <div  class="separateur_2"></div>
        <span class="nom">{{coktail.nom_objet }}</span>
        <span class="prix"> {{coktail.prix |floatformat:2}}€</span>
        <span class="ingredient">{{coktail.ingredient }}</span>
        <span class="origine">{{coktail.origine }}</span>
        <span class="commentaire">{{coktail.commentaire }}</span>
          {%endfor%}
    </div>



    <h2>Spiritueux</h2>
    <div class="section">
        {% for spiritueu  in spiritueux %}
        <div  class="separateur_2"></div>
        <span class="nom">{{spiritueu.nom_objet }}</span>
        <span class="prix"> {{spiritueu.prix |floatformat:2}}€</span>
        <span class="ingredient">{{spiritueu.ingredient }}</span>
        <span class="origine">{{spiritueu.origine }}</span>
        <span class="commentaire">{{spiritueu.commentaire }}</span>
          {%endfor%}
    </div>



    <h2>Coktail sans alcools</h2>
    <div class="section">
        {% for coktails_sans_alcool  in coktails_sans_alcools %}
        <div  class="separateur_2"></div>
        <span class="nom">{{coktails_sans_alcool.nom_objet }}</span>
        <span class="prix"> {{coktails_sans_alcool.prix |floatformat:2}}€</span>
        <span class="ingredient">{{coktails_sans_alcool.ingredient }}</span>
        <span class="origine">{{coktails_sans_alcool.origine }}</span>
        <span class="commentaire">{{coktails_sans_alcool.commentaire }}</span>
          {%endfor%}
    </div>



    <h2>Vins rouges</h2>
    <div class="section">
        {% for vins_rouge  in vins_rouges %}
        <div  class="separateur_2"></div>
        <span class="nom">{{vins_rouge.nom_objet }}</span>
        <span class="prix"> {{vins_rouge.prix |floatformat:2}}€</span>
        <span class="ingredient">{{vins_rouge.ingredient }}</span>
        <span class="origine">{{vins_rouge.origine }}</span>
        <span class="commentaire">{{vins_rouge.commentaire }}</span>
          {%endfor%}
    </div>


    <h2>Vins blancs</h2>
    <div class="section_bottom">
        {% for vins_blanc  in vins_blancs %}
        <div  class="separateur_2"></div>
        <span class="nom">{{vins_blanc.nom_objet }}</span>
        <span class="prix"> {{vins_blanc.prix |floatformat:2}}€</span>
        <span class="ingredient">{{vins_blanc.ingredient }}</span>
        <span class="origine">{{vins_blanc.origine }}</span>
        <span class="commentaire">{{vins_blanc.commentaire }}</span>
          {%endfor%}
    </div>
</div>
{% endblock content %}

diccionariosProyectos/base_siteV2/siteV2/main/templates/main/index.html
{{% load static%}

<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Acceuil</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main/style.css'%}">

</head>
<body>
    <h1> Restaurant</h1>
    <h2> <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300&display=swap" rel="stylesheet"> 90 Avenue des Alouettes <br> Parentis</h2>
    <div class="cover">
        <h3> <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300&display=swap" rel="stylesheet"> Cuisine Traditionnelle</h3>
        <div class="position_button">
            <a class="contact-button" href="tel:+33600000000"><img  src=" {% static 'main/images/icon_phone.png' %}">Réserver </a>
        </div>
    </div>


    <div class="infos">
        <h4>Menu</h4>

        <p>Dégustez une cuisine faite maison par le chef .</p>
        <div >
            <a class="menu-button"  href="{% url 'menu:index' %}"> voir le menu</a>
        </div>

        <h4>Horaire</h4>
        <p>Du lundi au Samedi</p>
        <p>Du Au déjeuner à partir de 12h</p>
        <p>DuAu dîner à partir de 19h.</p>

        <h4>Réservations</h4>
        <p>Pour toutes réservations,</p>
        <p>ou demande spéciale</p>
        <p>par téléphone au :  <a class="phone_numbers" href="tel:+33600000000">06 00 00 00 00</a>  .</p>

    </div>
        <div>
            <h5>Le Restaurant</h5>
            <p class="Infos_restaurant"> situé au coeur des Landes<br>
                au 90 avenue des Alouettes<br>
                dans le village de Parentis-En-Born</p>

            <div style="margin-left:8%;margin-top:18px;">
                <a   href=""><img  src=" {% static 'main/images/icons_facebook.png' %}"> </a>
                <a href=""><img  src=" {% static 'main/images/icon_instagram.png' %}"> </a>
            </div>

        </div>



</body>
</html>

diccionariosProyectos/base_siteV2/siteV2/menu/templates/menu/index.html
{%extends "alcool/base.html"%}
{%block content %}


<div class="ensemble">
    <h2>Entrées</h2>
    <div class="section">
        {% for entree in entrees %}
        <div  class="separateur_2"></div>
        <span class="nom">{{entree.nom_objet }}</span>
        <span class="prix"> {{entree.prix |floatformat:2}}€</span>
        <span class="commentaire">{{entree.ingredient }}</span>
        <span class="origine">{{entree.origine }}</span>
          {%endfor%}
    </div>

     <h2>Plats</h2>
    <div class="section">
        {% for plat in plats %}
        <div  class="separateur_2"></div>
        <span class="nom">{{plat.nom_objet }}</span>
        <span class="prix"> {{plat.prix |floatformat:2}}€</span>
        <span class="commentaire">{{plat.ingredient }}</span>
        <span class="origine">{{plat.origine }}</span>
          {%endfor%}
    </div>

    <h2>Suggestion Plats</h2>
    <div class="section">
        {% for suggestion_plat in suggestion_plats %}
        <div  class="separateur_2"></div>
        <span class="nom">{{suggestion_plat.nom_objet }}</span>
        <span class="prix"> {{suggestion_plat.prix |floatformat:2}}€</span>
        <span class="commentaire">{{suggestion_plat.ingredient }}</span>
        <span class="origine">{{suggestion_plat.origine }}</span>
          {%endfor%}
    </div>

     <h2>Desserts</h2>
    <div class="section">
        {% for dessert in desserts %}
        <div  class="separateur_2"></div>
        <span class="nom">{{dessert.nom_objet }}</span>
        <span class="prix"> {{dessert.prix |floatformat:2}}€</span>
        <span class="commentaire">{{dessert.ingredient }}</span>
        <span class="origine">{{dessert.origine }}</span>
          {%endfor%}
    </div>

     <h2>Menu Enfant </h2>
    <p style="padding-left:0.75rem"> Plat + dessert 18€</p>
    <div class="section_bottom">
        {% for plat_enfant in plat_enfants %}
        <div  class="separateur_2"></div>
        <span class="nom">{{plat_enfant.nom_objet }}</span>
        <span class="commentaire">{{plat_enfant.ingredient }}</span>
        <span class="origine">{{plat_enfant.origine }}</span>
          {%endfor%}
    </div>
</div>
{% endblock content %}