diccionariosProyectos/PizzaMamaDjango/PizzaMamaDjango/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls')),
    path('api/', include('menu.api_urls')),
]

diccionariosProyectos/PizzaMamaDjango/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name="index"),
]

diccionariosProyectos/PizzaMamaDjango/menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [
    path('pizzas', views.pizzas, name="pizzas"),
    path('salades', views.salades, name="salades"),
    path('pates', views.pates, name="pâtes"),
    path('desserts', views.desserts, name="desserts"),
]

diccionariosProyectos/PizzaMamaDjango/main/models.py
from django.db import models

# Create your models here.

diccionariosProyectos/PizzaMamaDjango/menu/models.py
from django.db import models
from django.forms import ModelForm


class Plat(models.Model):
    class PlatChoices(models.TextChoices):
        PIZZA = 'PI', 'Pizza'
        PATE = 'PA', 'Pâte'
        SALADE = 'SA', 'Salade'
        DESSERT = 'DE', 'Dessert'

    nom = models.CharField(max_length=200)
    categorie = models.CharField(
        max_length=2,
        choices=PlatChoices.choices,
        default=PlatChoices.PIZZA,
    )
    ingredients = models.CharField(max_length=400)
    prix = models.FloatField(default=0)
    vegetarienne = models.BooleanField(default=False)

    def __str__(self):
        return self.nom


class CategoriesPlatForm(ModelForm):
    class Meta:
        model = Plat
        fields = ['categorie']

diccionariosProyectos/PizzaMamaDjango/main/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'main/index.html')

diccionariosProyectos/PizzaMamaDjango/menu/views.py
from django.core import serializers
from django.http import HttpResponse
from django.shortcuts import render

from .models import Plat


# Create your views here.
def pizzas(request):
    plats = Plat.objects.filter(categorie='PI')
    return render(request, 'menu/pizzas.html', {'plats': plats})


def pates(request):
    plats = Plat.objects.filter(categorie='PA')
    return render(request, 'menu/pates.html', {'plats': plats})


def salades(request):
    plats = Plat.objects.filter(categorie='SA')
    return render(request, 'menu/salades.html', {'plats': plats})


def desserts(request):
    plats = Plat.objects.filter(categorie='DE')
    return render(request, 'menu/desserts.html', {'plats': plats})


def api_get_plats(request):
    plats = Plat.objects.all().order_by('prix')
    json = serializers.serialize("json", plats)
    return HttpResponse(json)

diccionariosProyectos/PizzaMamaDjango/main/templates/main/index.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Pizza Mama</title>
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
</head>
<body>
        <img src="{% static 'main/images/main_logo.png' %}" alt="main logo">
        <a href="{% url 'menu:pizzas' %}">Voir le menu</a>
</body>
</html>

diccionariosProyectos/PizzaMamaDjango/menu/templates/menu/base_menu.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block link-css %}{% endblock %}
    <script src="{% static 'menu/mes_scripts.js' %}" async></script>
</head>
<body>
    <div id="transition_page" class="transition active"></div>
    <div id="gradient-transparence"></div>
    <div id="sticky-div">
        <a href="{% url 'main:index' %}"><img id="small_logo" src="{% static 'menu/images/small_logo.png' %}" alt="small logo"></a><br>
        <br>
        {% block link-attribution %}{% endblock %}
        {% include "menu/includes/tags.html" %}
    </div>
    <div class="menu_list">
        {% for plat in plats %}
        <div class="menu_list_item">
            <div class="menu_list_titre_prix">
                <p class="menu_list_title">{{ plat.nom }}</p>
                <p class="menu_list_prix">{{ plat.prix | floatformat:2 }}€</p>
            </div>
            <div class="menu_list_ingredient">{{ plat.ingredients.title }}</div>
        </div>
        {% if plat.vegetarienne %}
        <div class="menu_list_badge">
            <span class="menu_list_badge">VEGETARIEN.NE</span>
        </div>
        {% endif %}
        <div class="espaceur"></div>
    {% endfor %}
     </div>
    <script>
        document.getElementById("mon-select").selectedIndex = {% block index %}{% endblock %};
    </script>
</body>
</html>

diccionariosProyectos/PizzaMamaDjango/menu/templates/menu/desserts.html
{% extends './base_menu.html' %}
{% load static %}
{% block title %}Menu des desserts{% endblock %}
{% block link-css %}<link rel="stylesheet" href="{% static 'menu/style_desserts.css' %}">{% endblock %}
{% block link-attribution %}<a class="attribution" href='https://fr.freepik.com/photos/assiette-restaurant'>Photo par KamranAydinov</a>{% endblock %}
{% block index %}"3"{% endblock %}

diccionariosProyectos/PizzaMamaDjango/menu/templates/menu/includes/tags.html
<label for="mon-select"></label>
<div class="formfield-select--container">
    <select id="mon-select" onchange="if (this.value) location.href=this.value">
{#        Enumérer les choix à partir de platChoices.choices #}
        <option value="{% url 'menu:pizzas' %}">Pizzas</option>
        <option value="{% url 'menu:salades' %}">Salades</option>
        <option value="{% url 'menu:pâtes' %}">Pâtes</option>
        <option value="{% url 'menu:desserts' %}">Desserts</option>
    </select>
</div>

diccionariosProyectos/PizzaMamaDjango/menu/templates/menu/pates.html
{% extends './base_menu.html' %}
{% load static %}
{% block title %}Menu des pâtes{% endblock %}
{% block link-css %}<link rel="stylesheet" href="{% static 'menu/style_pates.css' %}">{% endblock %}
{% block link-attribution %}<a class="attribution" href='https://fr.freepik.com/photos/cuisine-italienne'>Photo par freepik</a>{% endblock %}
{% block index %}"2"{% endblock %}

diccionariosProyectos/PizzaMamaDjango/menu/templates/menu/pizzas.html
{% extends './base_menu.html' %}
{% load static %}
{% block title %}Menu des pizzas{% endblock %}
{% block link-css %}<link rel="stylesheet" href="{% static "menu/style_pizzas.css" %}">{% endblock %}
{% block link-attribution %}<a class="attribution" href='#'></a>{% endblock %}
{% block index %}"0"{% endblock %}

diccionariosProyectos/PizzaMamaDjango/menu/templates/menu/salades.html
{% extends './base_menu.html' %}
{% load static %}
{% block title %}Menu des salades{% endblock %}
{% block link-css %}<link rel="stylesheet" href="{% static 'menu/style_salades.css' %}">{% endblock %}
{% block link-attribution %}<a class="attribution" href="https://fr.freepik.com/photos/legumes-frais">Photo par valeria_aksakova</a>{% endblock %}
{% block index %}"1"{% endblock %}