diccionariosProyectos/BaseRestaurant/BaseRestaurant/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls')),
    path('api/', include('menu.api_urls')),
    path('aperitif/', include('aperitif.urls')),
    path('vin/', include('vin.urls')),
    path('digestif/', include('digestif.urls')),
    path('', include('main.urls')),


]

diccionariosProyectos/BaseRestaurant/aperitif/urls.py
from django.urls import path
from . import views



app_name = 'aperitif'
urlpatterns = [
    path('', views.index,name="index"),
]

diccionariosProyectos/BaseRestaurant/digestif/urls.py
from django.urls import path
from . import views
app_name = 'digestif'
urlpatterns = [
    path('', views.index,name="index"),
]

diccionariosProyectos/BaseRestaurant/main/urls.py
from django.urls import path
from . import views
app_name = 'main'
urlpatterns = [
    path('', views.index,name="index"),
]

diccionariosProyectos/BaseRestaurant/menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'
urlpatterns = [
    path('', views.index, name="index"),

]

diccionariosProyectos/BaseRestaurant/vin/urls.py
from django.urls import path
from . import views
app_name = 'vin'
urlpatterns = [
    path('', views.index,name="index"),
]

diccionariosProyectos/BaseRestaurant/aperitif/models.py
from django.db import models

class CommonInfo(models.Model):
    nom = models.CharField(max_length=100)
    prix = models.FloatField(default=0)
    ingredient = models.CharField(max_length=200, blank=True)

    class Meta:
        abstract = True
    def __str__(self):
        return self.nom


class Tapa(CommonInfo):
    pass
class Champagne(CommonInfo):
    pass
class Cocktail (CommonInfo):
    pass
class Classique(CommonInfo):
    pass
class CocktailClassique(CommonInfo):
    pass
class SansAlcools(CommonInfo):
    pass
class Vodka(CommonInfo):
    pass
class Gin (CommonInfo):
    pass
class Whiskie(CommonInfo):
    pass

diccionariosProyectos/BaseRestaurant/aperitif/views.py
from django.shortcuts import render
from .models import Tapa,Champagne,Cocktail,Classique,CocktailClassique,SansAlcools,Vodka,Gin, Whiskie

def index(request):
    Tapas=Tapa.objects.all()
    Champagnes=Champagne.objects.all()
    Cocktails=Cocktail.objects.all()
    Classiques=Classique.objects.all()
    CocktailClassiques=CocktailClassique.objects.all()
    SansAlcoolss=SansAlcools.objects.all()
    Vodkas=Vodka.objects.all()
    Gins=Gin.objects.all()
    Whiskies=Whiskie.objects.all()

    return render(request, 'aperitif/index.html', {'Tapas': Tapas, 'Champagnes': Champagnes,
                                               'Cocktails': Cocktails, 'Classiques': Classiques,
                                               'CocktailClassiques': CocktailClassiques
                                                ,'SansAlcoolss': SansAlcoolss
                                                , 'Vodkas': Vodkas
                                                , 'Gins': Gins
                                                ,'Whiskies': Whiskies,})

diccionariosProyectos/BaseRestaurant/aperitif/templates/aperitif/index.html
{% load static %}
<html lang="fr">
    <head>
        <title>Menu Restaurant</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'aperitif/style.css'%}">
    </head>
    <body>
      <h1>Le  Restaurant</h1>
      <div>
            <img class="logo" src=" {% static 'aperitif/images/restaurant_orange.png' %}">
      </div>
      <div class="separateur"></div>
        <div class="ensemble">

            <div class="section">
                <h2>Tapas</h2>
                {% for tapa in Tapas %}
                <div  class="separateur_2"></div>
                <span class="nom">{{tapa.nom }}</span>
                <span class="prix"> {{tapa.prix |floatformat:2}}€</span>
                <span class="commentaire">{{tapa.ingredient }}</span>
                  {%endfor%}
            </div>


            <div class="section">
                <h2>Champagnes à la Coupe</h2>
                {% for champagne  in Champagnes %}
                <div  class="separateur_2"></div>
                <span class="nom">{{champagne.nom }}</span>
                <span class="prix"> {{champagne.prix |floatformat:2}}€</span>
                <span class="commentaire">{{champagne.ingredient }}</span>
                  {%endfor%}
            </div>

            <div class="section">
                <h2>Cocktails Créations</h2>
                {% for cocktail   in Cocktails %}
                <div  class="separateur_2"></div>
                <span class="nom">{{cocktail.nom }}</span>
                <span class="prix"> {{cocktail.prix |floatformat:2}}€</span>
                <span class="commentaire">{{cocktail.ingredient }}</span>
                  {%endfor%}
            </div>

            <div class="section">
                <h2>Grands Classiques</h2>
                {% for classique  in Classiques %}
                <div  class="separateur_2"></div>
                <span class="nom">{{classique.nom }}</span>
                <span class="prix"> {{classique.prix |floatformat:2}}€</span>
                <span class="commentaire">{{classique.ingredient }}</span>
                  {%endfor%}
            </div>

            <div class="section">
                <h2>Cocktails Classiques</h2>
                {% for cocktailClassique in CocktailClassiques %}
                <div  class="separateur_2"></div>
                <span class="nom">{{cocktailClassique.nom }}</span>
                <span class="prix"> {{cocktailClassique.prix |floatformat:2}}€</span>
                <span class="commentaire">{{cocktailClassique.ingredient }}</span>
                  {%endfor%}
            </div>

            <div class="section">
                <h2>Cocktails sans alcools</h2>
                {% for sansAlcools in SansAlcoolss%}
                <div  class="separateur_2"></div>
                <span class="nom">{{sansAlcools.nom }}</span>
                <span class="prix"> {{sansAlcools.prix |floatformat:2}}€</span>
                <span class="commentaire">{{sansAlcools.ingredient }}</span>
                  {%endfor%}
            </div>

            <div class="section_bottom">
                <h2>Vodka</h2>
                {% for vodka  in Vodkas%}
                <div  class="separateur_2"></div>
                <span class="nom">{{vodka.nom }}</span>
                <span class="prix"> {{vodka.prix |floatformat:2}}€</span>
                <span class="commentaire">{{vodka.ingredient }}</span>
                  {%endfor%}

            </div>
        </div>
            <div class="frame_position">
                    <a href="{% url 'main:index' %}"> Infos</a>
                    <a href="{% url 'menu:index' %}"> menu</a>
                    <a href="{% url 'aperitif:index' %}"> Apéritifs</a>
                    <a href="{% url 'vin:index' %}"> Vins</a>
                    <a href="{% url 'digestif:index' %}"> Digestifs</a>
            </div>


    </body>
</html>